apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.datasources.default.type }}
data:
  pass: {{ or .Values.datasources.default.password "" | b64enc }}
  AWS_ACCESS_KEY_ID: {{ or .Values.datasources.default.athena.aws_key "" | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ or .Values.datasources.default.athena.aws_secret "" | b64enc }}
  AWS_SESSION_TOKEN: {{ or .Values.datasources.default.athena.aws_token "" | b64enc }}