cubes:
  - name: product
    sql_table: Dim.BusinessType
    data_source: default

    joins: []

    dimensions:
      - name: BusinessTypeKey
        sql: BusinessTypeKey
        type: number
        primary_key: true
    
      - name:  CustomerTypeBudgetGroup
        sql:  BusinessView
        type: string

      - name:  Product
        sql:  Product
        type: string


    pre_aggregations:
      # Pre-aggregation definitions go here.
      # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started

