cubes:
  - name: source_application
    sql_table: Dim.DataLookupValue
    data_source: default

    joins: []

    dimensions:
      - name: DataLookupValueKey
        sql: DataLookupValueKey
        type: number
        primary_key: true
    
      - name:  source_application
        sql:  LookupValueName
        type: string


    pre_aggregations:
      # Pre-aggregation definitions go here.
      # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started

